#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 16
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 31

enum ts_symbol_identifiers {
  anon_sym_SBJ_DOT = 1,
  aux_sym_subject_name_token1 = 2,
  anon_sym_POUND = 3,
  anon_sym_DASH = 4,
  sym__group_h_start = 5,
  sym__tabular_h_start = 6,
  anon_sym_SEMI = 7,
  anon_sym_DOT = 8,
  aux_sym__item_indent_token1 = 9,
  sym_item_title_text = 10,
  sym__item_tag_start = 11,
  sym__decorator_start = 12,
  sym__continuation_start = 13,
  anon_sym_SLASH_SLASH = 14,
  sym_tri_marker = 15,
  sym_identifier = 16,
  sym_tag_content = 17,
  aux_sym_value_text_token1 = 18,
  sym__newline = 19,
  sym_source_file = 20,
  sym_subject = 21,
  sym_subject_header = 22,
  sym_subject_name = 23,
  sym_subject_tag = 24,
  sym_subject_tabular = 25,
  sym_subject_tabular_header = 26,
  sym_group = 27,
  sym_group_header = 28,
  sym_tabular_entry = 29,
  sym_tabular_header = 30,
  sym_tabular_value_line = 31,
  sym_item = 32,
  sym__item_indent = 33,
  sym_item_title = 34,
  sym_item_tag = 35,
  sym_decorator = 36,
  sym_continuation_line = 37,
  sym_id_clause = 38,
  sym_label_text = 39,
  sym_group_title = 40,
  sym_value_text = 41,
  sym_continuation_text = 42,
  sym__indent = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_subject_repeat1 = 45,
  aux_sym_subject_repeat2 = 46,
  aux_sym_group_repeat1 = 47,
  aux_sym_group_repeat2 = 48,
  aux_sym_tabular_value_line_repeat1 = 49,
  aux_sym_item_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SBJ_DOT] = "SBJ. ",
  [aux_sym_subject_name_token1] = "subject_name_token1",
  [anon_sym_POUND] = "# ",
  [anon_sym_DASH] = "- ",
  [sym__group_h_start] = "_group_h_start",
  [sym__tabular_h_start] = "_tabular_h_start",
  [anon_sym_SEMI] = "; ",
  [anon_sym_DOT] = ". ",
  [aux_sym__item_indent_token1] = "_item_indent_token1",
  [sym_item_title_text] = "item_title_text",
  [sym__item_tag_start] = "_item_tag_start",
  [sym__decorator_start] = "_decorator_start",
  [sym__continuation_start] = "_continuation_start",
  [anon_sym_SLASH_SLASH] = " // ",
  [sym_tri_marker] = "tri_marker",
  [sym_identifier] = "identifier",
  [sym_tag_content] = "tag_content",
  [aux_sym_value_text_token1] = "value_text_token1",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_subject] = "subject",
  [sym_subject_header] = "subject_header",
  [sym_subject_name] = "subject_name",
  [sym_subject_tag] = "subject_tag",
  [sym_subject_tabular] = "subject_tabular",
  [sym_subject_tabular_header] = "subject_tabular_header",
  [sym_group] = "group",
  [sym_group_header] = "group_header",
  [sym_tabular_entry] = "tabular_entry",
  [sym_tabular_header] = "tabular_header",
  [sym_tabular_value_line] = "tabular_value_line",
  [sym_item] = "item",
  [sym__item_indent] = "_item_indent",
  [sym_item_title] = "item_title",
  [sym_item_tag] = "item_tag",
  [sym_decorator] = "decorator",
  [sym_continuation_line] = "continuation_line",
  [sym_id_clause] = "id_clause",
  [sym_label_text] = "label_text",
  [sym_group_title] = "group_title",
  [sym_value_text] = "value_text",
  [sym_continuation_text] = "continuation_text",
  [sym__indent] = "_indent",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_subject_repeat1] = "subject_repeat1",
  [aux_sym_subject_repeat2] = "subject_repeat2",
  [aux_sym_group_repeat1] = "group_repeat1",
  [aux_sym_group_repeat2] = "group_repeat2",
  [aux_sym_tabular_value_line_repeat1] = "tabular_value_line_repeat1",
  [aux_sym_item_repeat1] = "item_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SBJ_DOT] = anon_sym_SBJ_DOT,
  [aux_sym_subject_name_token1] = aux_sym_subject_name_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym__group_h_start] = sym__group_h_start,
  [sym__tabular_h_start] = sym__tabular_h_start,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym__item_indent_token1] = aux_sym__item_indent_token1,
  [sym_item_title_text] = sym_item_title_text,
  [sym__item_tag_start] = sym__item_tag_start,
  [sym__decorator_start] = sym__decorator_start,
  [sym__continuation_start] = sym__continuation_start,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [sym_tri_marker] = sym_tri_marker,
  [sym_identifier] = sym_identifier,
  [sym_tag_content] = sym_tag_content,
  [aux_sym_value_text_token1] = aux_sym_value_text_token1,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_subject] = sym_subject,
  [sym_subject_header] = sym_subject_header,
  [sym_subject_name] = sym_subject_name,
  [sym_subject_tag] = sym_subject_tag,
  [sym_subject_tabular] = sym_subject_tabular,
  [sym_subject_tabular_header] = sym_subject_tabular_header,
  [sym_group] = sym_group,
  [sym_group_header] = sym_group_header,
  [sym_tabular_entry] = sym_tabular_entry,
  [sym_tabular_header] = sym_tabular_header,
  [sym_tabular_value_line] = sym_tabular_value_line,
  [sym_item] = sym_item,
  [sym__item_indent] = sym__item_indent,
  [sym_item_title] = sym_item_title,
  [sym_item_tag] = sym_item_tag,
  [sym_decorator] = sym_decorator,
  [sym_continuation_line] = sym_continuation_line,
  [sym_id_clause] = sym_id_clause,
  [sym_label_text] = sym_label_text,
  [sym_group_title] = sym_group_title,
  [sym_value_text] = sym_value_text,
  [sym_continuation_text] = sym_continuation_text,
  [sym__indent] = sym__indent,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_subject_repeat1] = aux_sym_subject_repeat1,
  [aux_sym_subject_repeat2] = aux_sym_subject_repeat2,
  [aux_sym_group_repeat1] = aux_sym_group_repeat1,
  [aux_sym_group_repeat2] = aux_sym_group_repeat2,
  [aux_sym_tabular_value_line_repeat1] = aux_sym_tabular_value_line_repeat1,
  [aux_sym_item_repeat1] = aux_sym_item_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SBJ_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_subject_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym__group_h_start] = {
    .visible = false,
    .named = true,
  },
  [sym__tabular_h_start] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__item_indent_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_item_title_text] = {
    .visible = true,
    .named = true,
  },
  [sym__item_tag_start] = {
    .visible = false,
    .named = true,
  },
  [sym__decorator_start] = {
    .visible = false,
    .named = true,
  },
  [sym__continuation_start] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tri_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_value_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_header] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_name] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_tabular] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_tabular_header] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_group_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tabular_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_tabular_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tabular_value_line] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym__item_indent] = {
    .visible = false,
    .named = true,
  },
  [sym_item_title] = {
    .visible = true,
    .named = true,
  },
  [sym_item_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation_line] = {
    .visible = true,
    .named = true,
  },
  [sym_id_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_label_text] = {
    .visible = true,
    .named = true,
  },
  [sym_group_title] = {
    .visible = true,
    .named = true,
  },
  [sym_value_text] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation_text] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tabular_value_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_continuation = 2,
  field_decorator = 3,
  field_group = 4,
  field_header = 5,
  field_id = 6,
  field_item = 7,
  field_label = 8,
  field_marker = 9,
  field_name = 10,
  field_path_id = 11,
  field_tabular = 12,
  field_tag = 13,
  field_text = 14,
  field_title = 15,
  field_value = 16,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_continuation] = "continuation",
  [field_decorator] = "decorator",
  [field_group] = "group",
  [field_header] = "header",
  [field_id] = "id",
  [field_item] = "item",
  [field_label] = "label",
  [field_marker] = "marker",
  [field_name] = "name",
  [field_path_id] = "path_id",
  [field_tabular] = "tabular",
  [field_tag] = "tag",
  [field_text] = "text",
  [field_title] = "title",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 3},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 1},
  [13] = {.index = 17, .length = 1},
  [14] = {.index = 18, .length = 1},
  [15] = {.index = 19, .length = 1},
  [16] = {.index = 20, .length = 1},
  [17] = {.index = 21, .length = 4},
  [18] = {.index = 25, .length = 2},
  [19] = {.index = 27, .length = 4},
  [20] = {.index = 31, .length = 4},
  [21] = {.index = 35, .length = 2},
  [22] = {.index = 37, .length = 2},
  [23] = {.index = 39, .length = 1},
  [24] = {.index = 40, .length = 6},
  [25] = {.index = 46, .length = 2},
  [26] = {.index = 48, .length = 1},
  [27] = {.index = 49, .length = 3},
  [28] = {.index = 52, .length = 2},
  [29] = {.index = 54, .length = 2},
  [30] = {.index = 56, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_header, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_header, 0},
    {field_value, 1},
  [4] =
    {field_group, 0},
  [5] =
    {field_tabular, 0},
  [6] =
    {field_item, 0},
  [7] =
    {field_title, 0},
  [8] =
    {field_header, 0},
    {field_tabular, 1, .inherited = true},
  [10] =
    {field_group, 1, .inherited = true},
    {field_header, 0},
    {field_item, 1, .inherited = true},
  [13] =
    {field_value, 1},
  [14] =
    {field_id, 2},
    {field_name, 1},
  [16] =
    {field_content, 1},
  [17] =
    {field_label, 1},
  [18] =
    {field_title, 1},
  [19] =
    {field_tag, 0},
  [20] =
    {field_decorator, 0},
  [21] =
    {field_decorator, 1, .inherited = true},
    {field_tabular, 1, .inherited = true},
    {field_tag, 1, .inherited = true},
    {field_title, 0},
  [25] =
    {field_tabular, 0, .inherited = true},
    {field_tabular, 1, .inherited = true},
  [27] =
    {field_group, 2, .inherited = true},
    {field_header, 0},
    {field_item, 2, .inherited = true},
    {field_tabular, 1, .inherited = true},
  [31] =
    {field_group, 0, .inherited = true},
    {field_group, 1, .inherited = true},
    {field_item, 0, .inherited = true},
    {field_item, 1, .inherited = true},
  [35] =
    {field_id, 2},
    {field_label, 1},
  [37] =
    {field_path_id, 2},
    {field_title, 1},
  [39] =
    {field_text, 1},
  [40] =
    {field_decorator, 0, .inherited = true},
    {field_decorator, 1, .inherited = true},
    {field_tabular, 0, .inherited = true},
    {field_tabular, 1, .inherited = true},
    {field_tag, 0, .inherited = true},
    {field_tag, 1, .inherited = true},
  [46] =
    {field_marker, 1},
    {field_value, 3},
  [48] =
    {field_continuation, 0},
  [49] =
    {field_continuation, 5, .inherited = true},
    {field_marker, 1},
    {field_value, 3},
  [52] =
    {field_marker, 2},
    {field_value, 4},
  [54] =
    {field_continuation, 0, .inherited = true},
    {field_continuation, 1, .inherited = true},
  [56] =
    {field_continuation, 6, .inherited = true},
    {field_marker, 2},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == ';') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == '.') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == '.') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 18:
      if (lookahead == ';') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == '>') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'B') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 'J') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'P') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'R') ADVANCE(23);
      END_STATE();
    case 25:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      END_STATE();
    case 26:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(49);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '-' &&
          lookahead != ':' &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(50);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == 'S') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SBJ_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_subject_name_token1);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__group_h_start);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__tabular_h_start);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__item_indent_token1);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '>') ADVANCE(19);
      if (lookahead == 'G') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__item_indent_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_item_title_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__item_tag_start);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__decorator_start);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__continuation_start);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_tri_marker);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_tri_marker);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_tri_marker);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_tag_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_value_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 29},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 29},
  [5] = {.lex_state = 29},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 29},
  [8] = {.lex_state = 29},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 29},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 29},
  [13] = {.lex_state = 29},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 29},
  [16] = {.lex_state = 29},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 29},
  [23] = {.lex_state = 29},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 29},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 29},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 29},
  [33] = {.lex_state = 29},
  [34] = {.lex_state = 29},
  [35] = {.lex_state = 29},
  [36] = {.lex_state = 29},
  [37] = {.lex_state = 29},
  [38] = {.lex_state = 29},
  [39] = {.lex_state = 29},
  [40] = {.lex_state = 29},
  [41] = {.lex_state = 29},
  [42] = {.lex_state = 29},
  [43] = {.lex_state = 18},
  [44] = {.lex_state = 18},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 51},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 18},
  [56] = {.lex_state = 18},
  [57] = {.lex_state = 51},
  [58] = {.lex_state = 18},
  [59] = {.lex_state = 51},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 51},
  [62] = {.lex_state = 18},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 28},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 27},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 26},
  [89] = {.lex_state = 28},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym__group_h_start] = ACTIONS(1),
    [sym__tabular_h_start] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym__item_indent_token1] = ACTIONS(1),
    [sym__item_tag_start] = ACTIONS(1),
    [sym__decorator_start] = ACTIONS(1),
    [sym__continuation_start] = ACTIONS(1),
    [sym_tri_marker] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(76),
    [sym_subject] = STATE(35),
    [sym_subject_header] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SBJ_DOT] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(11), 1,
      sym__group_h_start,
    ACTIONS(13), 1,
      sym__tabular_h_start,
    ACTIONS(15), 1,
      aux_sym__item_indent_token1,
    STATE(3), 1,
      sym_group_header,
    STATE(9), 1,
      sym_item_title,
    STATE(20), 1,
      aux_sym_group_repeat2,
    STATE(22), 1,
      aux_sym_group_repeat1,
    STATE(34), 1,
      sym_tabular_entry,
    STATE(41), 1,
      sym_group,
    STATE(42), 1,
      sym_item,
    STATE(43), 1,
      sym_tabular_header,
    STATE(81), 1,
      sym__item_indent,
    ACTIONS(9), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [42] = 13,
    ACTIONS(11), 1,
      sym__group_h_start,
    ACTIONS(13), 1,
      sym__tabular_h_start,
    ACTIONS(15), 1,
      aux_sym__item_indent_token1,
    STATE(2), 1,
      aux_sym_group_repeat1,
    STATE(3), 1,
      sym_group_header,
    STATE(9), 1,
      sym_item_title,
    STATE(15), 1,
      aux_sym_group_repeat2,
    STATE(34), 1,
      sym_tabular_entry,
    STATE(41), 1,
      sym_group,
    STATE(42), 1,
      sym_item,
    STATE(43), 1,
      sym_tabular_header,
    STATE(81), 1,
      sym__item_indent,
    ACTIONS(17), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [84] = 5,
    ACTIONS(21), 1,
      aux_sym__item_indent_token1,
    ACTIONS(23), 1,
      sym__continuation_start,
    STATE(10), 1,
      aux_sym_tabular_value_line_repeat1,
    STATE(19), 1,
      sym_continuation_line,
    ACTIONS(19), 9,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [108] = 10,
    ACTIONS(27), 1,
      sym__tabular_h_start,
    ACTIONS(30), 1,
      aux_sym__item_indent_token1,
    ACTIONS(32), 1,
      sym__item_tag_start,
    ACTIONS(35), 1,
      sym__decorator_start,
    STATE(5), 1,
      aux_sym_item_repeat1,
    STATE(23), 1,
      sym_tabular_entry,
    STATE(24), 1,
      sym_item_tag,
    STATE(26), 1,
      sym_decorator,
    STATE(43), 1,
      sym_tabular_header,
    ACTIONS(25), 4,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__newline,
  [142] = 5,
    ACTIONS(23), 1,
      sym__continuation_start,
    ACTIONS(40), 1,
      aux_sym__item_indent_token1,
    STATE(4), 1,
      aux_sym_tabular_value_line_repeat1,
    STATE(19), 1,
      sym_continuation_line,
    ACTIONS(38), 9,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [166] = 8,
    ACTIONS(11), 1,
      sym__group_h_start,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(46), 1,
      anon_sym_DASH,
    STATE(3), 1,
      sym_group_header,
    STATE(44), 1,
      sym_subject_tabular_header,
    STATE(31), 2,
      sym_group,
      aux_sym_subject_repeat2,
    ACTIONS(42), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
    STATE(13), 3,
      sym_subject_tag,
      sym_subject_tabular,
      aux_sym_subject_repeat1,
  [196] = 5,
    ACTIONS(23), 1,
      sym__continuation_start,
    ACTIONS(50), 1,
      aux_sym__item_indent_token1,
    STATE(10), 1,
      aux_sym_tabular_value_line_repeat1,
    STATE(19), 1,
      sym_continuation_line,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [220] = 10,
    ACTIONS(13), 1,
      sym__tabular_h_start,
    ACTIONS(54), 1,
      aux_sym__item_indent_token1,
    ACTIONS(56), 1,
      sym__item_tag_start,
    ACTIONS(58), 1,
      sym__decorator_start,
    STATE(11), 1,
      aux_sym_item_repeat1,
    STATE(23), 1,
      sym_tabular_entry,
    STATE(24), 1,
      sym_item_tag,
    STATE(26), 1,
      sym_decorator,
    STATE(43), 1,
      sym_tabular_header,
    ACTIONS(52), 4,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__newline,
  [254] = 5,
    ACTIONS(62), 1,
      aux_sym__item_indent_token1,
    ACTIONS(64), 1,
      sym__continuation_start,
    STATE(10), 1,
      aux_sym_tabular_value_line_repeat1,
    STATE(19), 1,
      sym_continuation_line,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [278] = 10,
    ACTIONS(13), 1,
      sym__tabular_h_start,
    ACTIONS(56), 1,
      sym__item_tag_start,
    ACTIONS(58), 1,
      sym__decorator_start,
    ACTIONS(69), 1,
      aux_sym__item_indent_token1,
    STATE(5), 1,
      aux_sym_item_repeat1,
    STATE(23), 1,
      sym_tabular_entry,
    STATE(24), 1,
      sym_item_tag,
    STATE(26), 1,
      sym_decorator,
    STATE(43), 1,
      sym_tabular_header,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__newline,
  [312] = 5,
    ACTIONS(23), 1,
      sym__continuation_start,
    ACTIONS(73), 1,
      aux_sym__item_indent_token1,
    STATE(8), 1,
      aux_sym_tabular_value_line_repeat1,
    STATE(19), 1,
      sym_continuation_line,
    ACTIONS(71), 9,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [336] = 8,
    ACTIONS(11), 1,
      sym__group_h_start,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(46), 1,
      anon_sym_DASH,
    STATE(3), 1,
      sym_group_header,
    STATE(44), 1,
      sym_subject_tabular_header,
    STATE(29), 2,
      sym_group,
      aux_sym_subject_repeat2,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
    STATE(21), 3,
      sym_subject_tag,
      sym_subject_tabular,
      aux_sym_subject_repeat1,
  [366] = 9,
    ACTIONS(79), 1,
      sym__group_h_start,
    ACTIONS(82), 1,
      aux_sym__item_indent_token1,
    STATE(3), 1,
      sym_group_header,
    STATE(9), 1,
      sym_item_title,
    STATE(14), 1,
      aux_sym_group_repeat2,
    STATE(41), 1,
      sym_group,
    STATE(42), 1,
      sym_item,
    STATE(81), 1,
      sym__item_indent,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [396] = 9,
    ACTIONS(11), 1,
      sym__group_h_start,
    ACTIONS(15), 1,
      aux_sym__item_indent_token1,
    STATE(3), 1,
      sym_group_header,
    STATE(9), 1,
      sym_item_title,
    STATE(14), 1,
      aux_sym_group_repeat2,
    STATE(41), 1,
      sym_group,
    STATE(42), 1,
      sym_item,
    STATE(81), 1,
      sym__item_indent,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [426] = 2,
    ACTIONS(89), 1,
      aux_sym__item_indent_token1,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__continuation_start,
      sym__newline,
  [442] = 5,
    ACTIONS(23), 1,
      sym__continuation_start,
    ACTIONS(93), 1,
      aux_sym__item_indent_token1,
    STATE(10), 1,
      aux_sym_tabular_value_line_repeat1,
    STATE(19), 1,
      sym_continuation_line,
    ACTIONS(91), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [464] = 5,
    ACTIONS(23), 1,
      sym__continuation_start,
    ACTIONS(97), 1,
      aux_sym__item_indent_token1,
    STATE(17), 1,
      aux_sym_tabular_value_line_repeat1,
    STATE(19), 1,
      sym_continuation_line,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [486] = 2,
    ACTIONS(101), 1,
      aux_sym__item_indent_token1,
    ACTIONS(99), 10,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__continuation_start,
      sym__newline,
  [502] = 9,
    ACTIONS(11), 1,
      sym__group_h_start,
    ACTIONS(15), 1,
      aux_sym__item_indent_token1,
    STATE(3), 1,
      sym_group_header,
    STATE(9), 1,
      sym_item_title,
    STATE(14), 1,
      aux_sym_group_repeat2,
    STATE(41), 1,
      sym_group,
    STATE(42), 1,
      sym_item,
    STATE(81), 1,
      sym__item_indent,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [532] = 5,
    ACTIONS(107), 1,
      anon_sym_POUND,
    ACTIONS(110), 1,
      anon_sym_DASH,
    STATE(44), 1,
      sym_subject_tabular_header,
    STATE(21), 3,
      sym_subject_tag,
      sym_subject_tabular,
      aux_sym_subject_repeat1,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__newline,
  [553] = 6,
    ACTIONS(115), 1,
      sym__tabular_h_start,
    ACTIONS(118), 1,
      aux_sym__item_indent_token1,
    STATE(22), 1,
      aux_sym_group_repeat1,
    STATE(34), 1,
      sym_tabular_entry,
    STATE(43), 1,
      sym_tabular_header,
    ACTIONS(113), 4,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__newline,
  [575] = 2,
    ACTIONS(122), 1,
      aux_sym__item_indent_token1,
    ACTIONS(120), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [588] = 2,
    ACTIONS(126), 1,
      aux_sym__item_indent_token1,
    ACTIONS(124), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [601] = 2,
    ACTIONS(130), 1,
      aux_sym__item_indent_token1,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [614] = 2,
    ACTIONS(134), 1,
      aux_sym__item_indent_token1,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [627] = 2,
    ACTIONS(138), 1,
      aux_sym__item_indent_token1,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [640] = 2,
    ACTIONS(142), 1,
      aux_sym__item_indent_token1,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__item_tag_start,
      sym__decorator_start,
      sym__newline,
  [653] = 4,
    ACTIONS(11), 1,
      sym__group_h_start,
    STATE(3), 1,
      sym_group_header,
    STATE(30), 2,
      sym_group,
      aux_sym_subject_repeat2,
    ACTIONS(144), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [669] = 4,
    ACTIONS(148), 1,
      sym__group_h_start,
    STATE(3), 1,
      sym_group_header,
    STATE(30), 2,
      sym_group,
      aux_sym_subject_repeat2,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [685] = 4,
    ACTIONS(11), 1,
      sym__group_h_start,
    STATE(3), 1,
      sym_group_header,
    STATE(30), 2,
      sym_group,
      aux_sym_subject_repeat2,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__newline,
  [701] = 2,
    ACTIONS(153), 1,
      aux_sym__item_indent_token1,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__newline,
  [712] = 1,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__newline,
  [721] = 2,
    ACTIONS(159), 1,
      aux_sym__item_indent_token1,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__newline,
  [732] = 5,
    ACTIONS(5), 1,
      anon_sym_SBJ_DOT,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 1,
      sym__newline,
    STATE(7), 1,
      sym_subject_header,
    STATE(37), 2,
      sym_subject,
      aux_sym_source_file_repeat1,
  [749] = 1,
    ACTIONS(165), 6,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__newline,
  [758] = 5,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 1,
      anon_sym_SBJ_DOT,
    ACTIONS(172), 1,
      sym__newline,
    STATE(7), 1,
      sym_subject_header,
    STATE(37), 2,
      sym_subject,
      aux_sym_source_file_repeat1,
  [775] = 2,
    ACTIONS(177), 1,
      aux_sym__item_indent_token1,
    ACTIONS(175), 5,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__tabular_h_start,
      sym__newline,
  [786] = 1,
    ACTIONS(179), 6,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__newline,
  [795] = 1,
    ACTIONS(181), 6,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      anon_sym_POUND,
      anon_sym_DASH,
      sym__group_h_start,
      sym__newline,
  [804] = 2,
    ACTIONS(185), 1,
      aux_sym__item_indent_token1,
    ACTIONS(183), 4,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__newline,
  [814] = 2,
    ACTIONS(189), 1,
      aux_sym__item_indent_token1,
    ACTIONS(187), 4,
      ts_builtin_sym_end,
      anon_sym_SBJ_DOT,
      sym__group_h_start,
      sym__newline,
  [824] = 4,
    ACTIONS(191), 1,
      anon_sym_SEMI,
    ACTIONS(193), 1,
      aux_sym__item_indent_token1,
    STATE(27), 1,
      sym_tabular_value_line,
    STATE(82), 1,
      sym__indent,
  [837] = 4,
    ACTIONS(191), 1,
      anon_sym_SEMI,
    ACTIONS(193), 1,
      aux_sym__item_indent_token1,
    STATE(33), 1,
      sym_tabular_value_line,
    STATE(82), 1,
      sym__indent,
  [850] = 3,
    ACTIONS(195), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(197), 1,
      sym__newline,
    STATE(87), 1,
      sym_id_clause,
  [860] = 3,
    ACTIONS(195), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(199), 1,
      sym__newline,
    STATE(65), 1,
      sym_id_clause,
  [870] = 3,
    ACTIONS(195), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(201), 1,
      sym__newline,
    STATE(79), 1,
      sym_id_clause,
  [880] = 3,
    ACTIONS(195), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(203), 1,
      sym__newline,
    STATE(64), 1,
      sym_id_clause,
  [890] = 1,
    ACTIONS(205), 2,
      anon_sym_SLASH_SLASH,
      sym__newline,
  [895] = 2,
    ACTIONS(207), 1,
      aux_sym_value_text_token1,
    STATE(78), 1,
      sym_value_text,
  [902] = 2,
    ACTIONS(209), 1,
      aux_sym_subject_name_token1,
    STATE(47), 1,
      sym_group_title,
  [909] = 2,
    ACTIONS(211), 1,
      aux_sym_subject_name_token1,
    STATE(48), 1,
      sym_label_text,
  [916] = 2,
    ACTIONS(211), 1,
      aux_sym_subject_name_token1,
    STATE(46), 1,
      sym_label_text,
  [923] = 1,
    ACTIONS(213), 2,
      anon_sym_SLASH_SLASH,
      sym__newline,
  [928] = 1,
    ACTIONS(215), 2,
      anon_sym_SEMI,
      aux_sym__item_indent_token1,
  [933] = 1,
    ACTIONS(217), 2,
      anon_sym_SEMI,
      aux_sym__item_indent_token1,
  [938] = 2,
    ACTIONS(207), 1,
      aux_sym_value_text_token1,
    STATE(71), 1,
      sym_value_text,
  [945] = 1,
    ACTIONS(219), 2,
      anon_sym_SEMI,
      aux_sym__item_indent_token1,
  [950] = 2,
    ACTIONS(221), 1,
      aux_sym_value_text_token1,
    STATE(85), 1,
      sym_continuation_text,
  [957] = 1,
    ACTIONS(223), 2,
      anon_sym_SLASH_SLASH,
      sym__newline,
  [962] = 2,
    ACTIONS(207), 1,
      aux_sym_value_text_token1,
    STATE(77), 1,
      sym_value_text,
  [969] = 1,
    ACTIONS(225), 2,
      anon_sym_SEMI,
      aux_sym__item_indent_token1,
  [974] = 2,
    ACTIONS(227), 1,
      aux_sym_subject_name_token1,
    STATE(45), 1,
      sym_subject_name,
  [981] = 1,
    ACTIONS(229), 1,
      sym__newline,
  [985] = 1,
    ACTIONS(231), 1,
      sym__newline,
  [989] = 1,
    ACTIONS(233), 1,
      sym_tri_marker,
  [993] = 1,
    ACTIONS(235), 1,
      sym__newline,
  [997] = 1,
    ACTIONS(237), 1,
      anon_sym_DOT,
  [1001] = 1,
    ACTIONS(239), 1,
      sym__newline,
  [1005] = 1,
    ACTIONS(241), 1,
      sym__newline,
  [1009] = 1,
    ACTIONS(243), 1,
      sym__newline,
  [1013] = 1,
    ACTIONS(245), 1,
      sym_tag_content,
  [1017] = 1,
    ACTIONS(247), 1,
      sym_tri_marker,
  [1021] = 1,
    ACTIONS(249), 1,
      anon_sym_DOT,
  [1025] = 1,
    ACTIONS(251), 1,
      anon_sym_DOT,
  [1029] = 1,
    ACTIONS(253), 1,
      ts_builtin_sym_end,
  [1033] = 1,
    ACTIONS(255), 1,
      sym__newline,
  [1037] = 1,
    ACTIONS(257), 1,
      sym__newline,
  [1041] = 1,
    ACTIONS(259), 1,
      sym__newline,
  [1045] = 1,
    ACTIONS(261), 1,
      sym__newline,
  [1049] = 1,
    ACTIONS(263), 1,
      sym_item_title_text,
  [1053] = 1,
    ACTIONS(265), 1,
      anon_sym_SEMI,
  [1057] = 1,
    ACTIONS(267), 1,
      sym_tri_marker,
  [1061] = 1,
    ACTIONS(269), 1,
      sym__newline,
  [1065] = 1,
    ACTIONS(271), 1,
      sym__newline,
  [1069] = 1,
    ACTIONS(273), 1,
      sym__newline,
  [1073] = 1,
    ACTIONS(275), 1,
      sym__newline,
  [1077] = 1,
    ACTIONS(277), 1,
      sym_identifier,
  [1081] = 1,
    ACTIONS(279), 1,
      sym_tag_content,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 166,
  [SMALL_STATE(8)] = 196,
  [SMALL_STATE(9)] = 220,
  [SMALL_STATE(10)] = 254,
  [SMALL_STATE(11)] = 278,
  [SMALL_STATE(12)] = 312,
  [SMALL_STATE(13)] = 336,
  [SMALL_STATE(14)] = 366,
  [SMALL_STATE(15)] = 396,
  [SMALL_STATE(16)] = 426,
  [SMALL_STATE(17)] = 442,
  [SMALL_STATE(18)] = 464,
  [SMALL_STATE(19)] = 486,
  [SMALL_STATE(20)] = 502,
  [SMALL_STATE(21)] = 532,
  [SMALL_STATE(22)] = 553,
  [SMALL_STATE(23)] = 575,
  [SMALL_STATE(24)] = 588,
  [SMALL_STATE(25)] = 601,
  [SMALL_STATE(26)] = 614,
  [SMALL_STATE(27)] = 627,
  [SMALL_STATE(28)] = 640,
  [SMALL_STATE(29)] = 653,
  [SMALL_STATE(30)] = 669,
  [SMALL_STATE(31)] = 685,
  [SMALL_STATE(32)] = 701,
  [SMALL_STATE(33)] = 712,
  [SMALL_STATE(34)] = 721,
  [SMALL_STATE(35)] = 732,
  [SMALL_STATE(36)] = 749,
  [SMALL_STATE(37)] = 758,
  [SMALL_STATE(38)] = 775,
  [SMALL_STATE(39)] = 786,
  [SMALL_STATE(40)] = 795,
  [SMALL_STATE(41)] = 804,
  [SMALL_STATE(42)] = 814,
  [SMALL_STATE(43)] = 824,
  [SMALL_STATE(44)] = 837,
  [SMALL_STATE(45)] = 850,
  [SMALL_STATE(46)] = 860,
  [SMALL_STATE(47)] = 870,
  [SMALL_STATE(48)] = 880,
  [SMALL_STATE(49)] = 890,
  [SMALL_STATE(50)] = 895,
  [SMALL_STATE(51)] = 902,
  [SMALL_STATE(52)] = 909,
  [SMALL_STATE(53)] = 916,
  [SMALL_STATE(54)] = 923,
  [SMALL_STATE(55)] = 928,
  [SMALL_STATE(56)] = 933,
  [SMALL_STATE(57)] = 938,
  [SMALL_STATE(58)] = 945,
  [SMALL_STATE(59)] = 950,
  [SMALL_STATE(60)] = 957,
  [SMALL_STATE(61)] = 962,
  [SMALL_STATE(62)] = 969,
  [SMALL_STATE(63)] = 974,
  [SMALL_STATE(64)] = 981,
  [SMALL_STATE(65)] = 985,
  [SMALL_STATE(66)] = 989,
  [SMALL_STATE(67)] = 993,
  [SMALL_STATE(68)] = 997,
  [SMALL_STATE(69)] = 1001,
  [SMALL_STATE(70)] = 1005,
  [SMALL_STATE(71)] = 1009,
  [SMALL_STATE(72)] = 1013,
  [SMALL_STATE(73)] = 1017,
  [SMALL_STATE(74)] = 1021,
  [SMALL_STATE(75)] = 1025,
  [SMALL_STATE(76)] = 1029,
  [SMALL_STATE(77)] = 1033,
  [SMALL_STATE(78)] = 1037,
  [SMALL_STATE(79)] = 1041,
  [SMALL_STATE(80)] = 1045,
  [SMALL_STATE(81)] = 1049,
  [SMALL_STATE(82)] = 1053,
  [SMALL_STATE(83)] = 1057,
  [SMALL_STATE(84)] = 1061,
  [SMALL_STATE(85)] = 1065,
  [SMALL_STATE(86)] = 1069,
  [SMALL_STATE(87)] = 1073,
  [SMALL_STATE(88)] = 1077,
  [SMALL_STATE(89)] = 1081,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 1, 0, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_value_line, 7, 0, 30),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tabular_value_line, 7, 0, 30),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 24),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 24), SHIFT_REPEAT(53),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_item_repeat1, 2, 0, 24),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 24), SHIFT_REPEAT(72),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 24), SHIFT_REPEAT(73),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_value_line, 6, 0, 28),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tabular_value_line, 6, 0, 28),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_value_line, 6, 0, 27),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tabular_value_line, 6, 0, 27),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 7),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item, 1, 0, 7),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tabular_value_line_repeat1, 2, 0, 29),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tabular_value_line_repeat1, 2, 0, 29),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tabular_value_line_repeat1, 2, 0, 29), SHIFT_REPEAT(59),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 2, 0, 17),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item, 2, 0, 17),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_value_line, 5, 0, 25),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tabular_value_line, 5, 0, 25),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat2, 2, 0, 20),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat2, 2, 0, 20), SHIFT_REPEAT(51),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_group_repeat2, 2, 0, 20), SHIFT_REPEAT(81),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 9),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation_line, 3, 0, 12),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_continuation_line, 3, 0, 12),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator, 6, 0, 27),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator, 6, 0, 27),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator, 5, 0, 25),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator, 5, 0, 25),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tabular_value_line_repeat1, 1, 0, 26),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tabular_value_line_repeat1, 1, 0, 26),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 19),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 18),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 18), SHIFT_REPEAT(53),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_group_repeat1, 2, 0, 18),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 1, 0, 5),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_item_repeat1, 1, 0, 5),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 1, 0, 15),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_item_repeat1, 1, 0, 15),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_tag, 3, 0, 12),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_tag, 3, 0, 12),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 1, 0, 16),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_item_repeat1, 1, 0, 16),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_entry, 2, 0, 3),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tabular_entry, 2, 0, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_title, 3, 0, 23),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_title, 3, 0, 23),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat2, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_repeat2, 2, 0, 0), SHIFT_REPEAT(51),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_header, 3, 0, 14),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_header, 3, 0, 14),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_tabular, 2, 0, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 1, 0, 5),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_group_repeat1, 1, 0, 5),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_header, 3, 0, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_header, 4, 0, 22),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_header, 4, 0, 22),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_header, 4, 0, 11),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_tag, 3, 0, 12),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat2, 1, 0, 4),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_group_repeat2, 1, 0, 4),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat2, 1, 0, 6),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_group_repeat2, 1, 0, 6),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_text, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_name, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_tabular_header, 4, 0, 21),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_tabular_header, 3, 0, 13),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_header, 3, 0, 13),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_title, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_header, 4, 0, 21),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_text, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [253] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_clause, 2, 0, 10),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation_text, 1, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rep(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
