let T = ./Types.dhall

-- Generated by Claude:
--
-- The Snodgrass Institute for Mundane Phenomena
-- A comprehensive test fixture covering all value types, progress states,
-- level structures, and annotation helpers, for UI rendering tests.
-- Est. 1987 by Prof. Archibald Snodgrass, who dedicated 34 years to the
-- rigorous scientific study of everyday inconveniences.

in

    T.collapse
        { id = "snodgrass-institute"
        , name = "Snodgrass Institute for Mundane Phenomena"
        }

        ( T.group "General Overview" [ "00-overview" ]
            [ T.kv_ "Founded" (T.v_i +1987)
            , T.kv_ "Active Staff Members" (T.v_n 47)
            , T.kv_ "Annual Budget (£ million)" (T.v_f 3.14)
            , T.kv_ "Current Director" (T.v_t "Prof. Archibald Snodgrass VII")
            , T.kv_ "Location of Last Known Stapler" (T.v_empty)
            , T.kv_ "Source of Ongoing Funding" (T.v_unk)
            , T.kv_ "Achievement Certificates (ref)" (T.v_pi { done = +2, total = +5 })
              // T.inj/self [ "05-levels", "01-certs" ]
            ]

        -- All PROC states -------------------------------------------------------

        # T.groupStats "Experiments: Status Board" [ "01-experiments" ]
            [ T.kv_ "Toast Trajectory Study (butter-side-down)" (T.p_doing)
              // T.inj/det "1000 drops planned; 847 confirmed butter-down so far"
            , T.kv_ "Queue Migration Theorem: Phase III" (T.p_todo)
              // T.inj/det "Why does the other queue always move faster?"
            , T.kv_ "Remote Control Uncertainty Principle" (T.p_now)
              // T.inj/det "CRITICAL: whereabouts unknown; last seen near sofa (2019)"
            , T.kv_ "Tea Temperature Optimality Survey" (T.p_wait)
              // T.inj/det "Awaiting 400 additional teapot deliveries for Phase II"
            , T.kv_ "Optimal Biscuit Dunking Protocol" (T.p_done)
              // T.inj/det "Result: 4.2 sec in 73°C tea (chocolate digestive only)"
              // T.inj/date { mon = +11, day = +3, year = +2024 }
            , T.kv_ "Left Sock Weather Correlation Study" (T.p_later)
              // T.inj/det "Deferred: awaiting meteorological cooperation agreement"
            , T.kv_ "Elevator Button Pressing Efficacy" (T.p_canceled)
              // T.inj/det "Terminated: buttons disconnected since 1994 (see memo #4471)"
            , T.kv_ "Fridge Light Observation Project" (T.p_locked)
              // T.inj/det "Blocked by ethics committee (Schrödinger compliance issue)"
            ]

        -- Measurement value types ------------------------------------------------

        # T.group "Measurement Lab: Units" [ "02-measurements" ]
            [ T.kv_ "Teaspoons Lost Per Year" (T.v_mes +147 "spoons")
            , T.kv_ "Average Sock-Search Duration" (T.v_mesd 3.7 "min")
            , T.kv_ "Annoyance Factor Change (positive delta)" (T.v_mesx +1 2.5 "units")
            , T.kv_ "Staff Patience Erosion (negative delta)" (T.v_mesx -1 8.3 "units")
            , T.kv_ "Useless Meetings Per Day" (T.v_per +5 "day")
            , T.kv_ "Paperclip Consumption" (T.v_perd 12.5 "hour")
            , T.kv_ "Forms Approved (pct int measure)" (T.v_pct_mes +73)
            , T.kv_ "Forms Rejected (pct double measure)" (T.v_pct_mesd 41.5)
            , T.kv_ "Efficiency Improvement Delta (pct positive)" (T.v_pct_mesx +1 2.3)
            , T.kv_ "Budget Burn Rate (pct negative)" (T.v_pct_mesx -1 5.7)
            ]

        # T.group "Measurement Lab: Percentages" [ "02-measurements", "00-percentages" ]
            [ T.kv_ "Experiment Success Rate (pct 0.0..1.0)" (T.v_pct 0.42)
            , T.kv_ "Bureaucracy Overhead (pcti 0..100)" (T.v_pcti +87)
            , T.kv_ "Tea Satisfaction Index (pctx positive)" (T.v_pctx +1 12.5)
            , T.kv_ "Staff Enthusiasm Change (pctx negative)" (T.v_pctx -1 3.14)
            , T.kv_ "Hypothesis Confirmed" (T.v_pct_done)
            , T.kv_ "Hypothesis Not-Yet-Falsified" (T.v_pct_none)
            , T.kv_ "Funding Consumed" (T.v_pcti_done)
            , T.kv_ "Useful Output Delivered" (T.v_pcti_none)
            ]

        # T.group "Measurement Lab: Bool & Fractions" [ "02-measurements", "01-booleans" ]
            [ T.kv_ "Coffee Machine: Operational" (T.v_done)
            , T.kv_ "WiFi Connection: Reliable" (T.v_none)
            , T.kv_ "Last Grant Application: Approved (pi 1/1)" (T.v_done_)
            , T.kv_ "Parking Space: Obtained (pi 0/1)" (T.v_none_)
            , T.kv_ "Last Committee Vote: Conclusive (pi 0/0)" (T.v_vone_)
            , T.kv_ "Quarterly Reports Submitted (pi int)" (T.v_pi { done = +7, total = +12 })
            , T.kv_ "Skill Points Allocated (pd double)" (T.v_pd { done = 2.5, total = 5.0 })
            ]

        -- Temporal values -------------------------------------------------------

        # T.group "Temporal Records" [ "03-time" ]
            [ T.kv_ "Duration of Last Board Meeting" (T.v_time { hrs = +3, min = +47, sec = +22 })
            , T.kv_ "Date of Last Sensible Decision" (T.v_date { mon = +4, day = +1, year = +2019 })
            , T.kv_ "Next Fire Drill (relt: more than)" (T.v_relt (T.rel_more_than T.TIME { hrs = +2, min = +0, sec = +0 }))
            , T.kv_ "Acceptable Tea Break Window (relt: less than)" (T.v_relt (T.rel_less_than T.TIME { hrs = +0, min = +15, sec = +0 }))
            , T.kv_ "Statutory Board Meeting Length (relt: exact)" (T.v_relt (T.rel_exact T.TIME { hrs = +1, min = +30, sec = +0 }))
            ]

        -- Ranges and numeric relations -------------------------------------------

        # T.group "Ranges & Numeric Relations" [ "04-ranges" ]
            [ T.kv_ "Acceptable Pencil Length (rngi, mm)" (T.v_rng { from = +120, to = +190 })
            , T.kv_ "Ideal Coffee Temperature (rngd, °C)" (T.v_rngd { from = 63.0, to = 79.5 })
            , T.kv_ "Minimum Forms Per Day (reli: more than)" (T.v_reli (T.rel_more_than Integer +3))
            , T.kv_ "Maximum Acceptable Queue (reli: less than)" (T.v_reli (T.rel_less_than Integer +10))
            , T.kv_ "Minimum Staff Satisfaction Score (reld: more than)" (T.v_reld (T.rel_more_than Double 3.5))
            , T.kv_ "Maximum Acceptable Library Noise dB (reld: less than)" (T.v_reld (T.rel_less_than Double 42.0))
            , T.kv_ "Annual Forms Processing Target (reln: exact)" (T.v_reln (T.rel_exact Natural 100))
            ]

        -- Level/progress structures ----------------------------------------------

        # T.group_ "Level Progressions" [ "05-levels" ]

        # T.groupStats "Skill Tracks" [ "05-levels", "00-skills" ]
            [ T.kv_ "Rubber Stamp Proficiency (lvls: text gives)"
                (T.v_lvls
                    { reached = +3
                    , levels =
                        [ { gives = "Basic Approval Authority" } // T.inj/no_date
                        , { gives = "+20 Stamp Speed" } // T.inj/date { mon = +3, day = +15, year = +2024 }
                        , { gives = "Unconditional Denial Mastery" } // T.inj/date { mon = +9, day = +7, year = +2024 }
                        , { gives = "Cross-Departmental Stamp Rights" } // T.inj/no_date
                        , { gives = "Legendary: The Phantom Stamp" } // T.inj/no_date
                        ]
                    }
                )
            , T.kv_ "Procrastination Mastery (lvli: int maximum)"
                (T.v_lvli
                    { reached = +4
                    , levels =
                        [ { maximum = +10,  name = "I'll Do It Tomorrow" } // T.inj/no_date
                        , { maximum = +25,  name = "Strategic Delay" } // T.inj/no_date
                        , { maximum = +50,  name = "Extended Contemplation" } // T.inj/no_date
                        , { maximum = +100, name = "Masterful Deferral" } // T.inj/date { mon = +1, day = +3, year = +2025 }
                        , { maximum = +200, name = "Enlightened Inaction" } // T.inj/no_date
                        ]
                    }
                )
            , T.kv_ "Tea Brewing Expertise (lvld: double maximum)"
                (T.v_lvld
                    { reached = 2.5
                    , levels =
                        [ { maximum = 1.0, name = "Bag-in-Cup" } // T.inj/no_date
                        , { maximum = 2.0, name = "Loose Leaf Aware" } // T.inj/no_date
                        , { maximum = 3.0, name = "Temperature Control" } // T.inj/date { mon = +6, day = +12, year = +2023 }
                        , { maximum = 4.0, name = "Steeping Time Precision" } // T.inj/no_date
                        , { maximum = 5.0, name = "Grandmaster of the Kettle" } // T.inj/no_date
                        ]
                    }
                )
            , T.kv_ "Form Processing Level (lvlc: current/max)"
                (T.v_lvlc { reached = +7, levels = +10, current = +7, maxcurrent = +10 })
            , T.kv_ "Queue Management Certification (lvlp: per-level PROC)"
                (T.v_lvlp
                    { levels =
                        [ { proc = T.p_done_,   name = "Single Queue Basics" }   // T.inj/no_date
                        , { proc = T.p_done_,   name = "Multi-Lane Queuing" }    // T.inj/date { mon = +2, day = +28, year = +2023 }
                        , { proc = T.p_doing_,  name = "Predictive Queue Analysis" } // T.inj/no_date
                        , { proc = T.p_todo_,   name = "Zen Queue Management" }  // T.inj/no_date
                        , { proc = T.p_locked_, name = "Queue Singularity (requires Zen)" } // T.inj/no_date
                        ]
                    }
                )
            , T.kv_ "Budget Expenditure Authorization (lvlio: optional int)"
                (T.v_lvlio
                    { reached = +3
                    , levels =
                        [ { maximum = Some +100,    name = "Petty Cash" } // T.inj/no_date
                        , { maximum = Some +5000,   name = "Department Discretionary" } // T.inj/no_date
                        , { maximum = Some +50000,  name = "Project Budget" } // T.inj/date { mon = +8, day = +1, year = +2024 }
                        , { maximum = None Integer,  name = "Unlimited (Theoretical)" } // T.inj/no_date
                        ]
                    }
                )
            ]

        # T.groupColl "Achievement Certificates" [ "05-levels", "01-certs" ]

            -- stat_i, stat_pct, count injections

            [ T.kv_ "Certificate of Participation" (T.v_done)
              // T.inj/stat_i +1
            , T.kv_ "Certificate of Mild Effort" (T.v_done)
              // T.inj/stat_i +1
              // T.inj/count +3
            , T.kv_ "Certificate of Occasional Presence" (T.p_doing)
              // T.inj/stat_pct 0.5
            , T.kv_ "Certificate of Marginal Contribution" (T.v_none)
              // T.inj/stat_i +0
            , T.kv_ "Certificate of Legendary Inaction" (T.v_none)
              // T.inj/stat_pct 0.0
            ]

        -- Annotation helpers: tags, tab, tabs, det, date, self ------------------

        # T.groupStats "Annotated Field Notes" [ "06-field-notes" ]
            [ T.kv_ "Observation #1: The Missing Stapler Phenomenon" (T.p_doing)
              // T.inj/tags [ "urgent", "recurring", "unexplained" ]
              // T.inj/tab "assigned_to" (T.v_t "Dr. Fumbleton")

            , T.kv_ "Experiment Delta-7: Kettle Behaviour Study" (T.v_pi { done = +3, total = +5 })
              // T.inj/det "Comprehensive boiling pattern analysis under controlled observation"
              // T.inj/date { mon = +9, day = +12, year = +2024 }
              -- Multiple tabular columns via inj/tabs
              // T.inj/tabs
                    [ { key = "lead_researcher",  value = T.tag (T.v_t "Dr. Kettleworth") }
                    , { key = "budget_remaining", value = T.tag (T.v_mes +47 "GBP") }
                    , { key = "water_temp",       value = T.tag (T.v_mesd 97.3 "°C") }
                    , { key = "steeping_time",    value = T.tag (T.v_time { hrs = +0, min = +3, sec = +45 }) }
                    ]

            , T.kv_ "Form #88-B: Inter-departmental Nudge Request" (T.p_todo)
              // T.inj/tags [ "form", "nudge", "pending-since-1998" ]

            , T.kv_ "Cross-Reference: Biscuit Dunking Study" (T.v_empty)
              // T.inj/self [ "01-experiments" ]
              // T.inj/tag "cross-ref"

            , T.kv_ "Proprietary Finding #44" (T.v_unk)
              // T.inj/det "Details classified — patent application pending (filed: never)"

            -- v_proc used with a PROC_ value directly (same as p_doing, different syntax)
            , T.kv_ "PROC value via v_proc helper" (T.v_proc T.p_doing_)
              // T.inj/det "Same result as p_doing; demonstrates v_proc + PROC_ form"
            ]

        )
    //
    { tabular =
        [ { key = "established",     value = T.tag (T.v_date { mon = +3, day = +17, year = +1987 }) }
        , { key = "location",        value = T.tag (T.v_t "Upper Tufnell Park, London") }
        , { key = "staff_count",     value = T.tag (T.v_i +47) }
        , { key = "papers_published", value = T.tag (T.v_i +3) }
        , { key = "papers_retracted", value = T.tag (T.v_i +3) }
        , { key = "net_useful_output", value = T.tag T.v_empty }
        ]
    , tags = [ "Science", "Peculiar", "British" ]
    }
